[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.hw4.model.Post[]" --]
[#-- @ftlvariable name="uri" type="String" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.hw4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.hw4.model.User" --]
